name: build & push

on: [push]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Start Docker
        run : |
          docker compose up -d --build
          curl -sSL "https://github.com/fullstorydev/grpcurl/releases/download/v1.8.7/grpcurl_1.8.7_linux_x86_64.tar.gz"
          tar -xz -C /usr/local/bin
          grpcurl -version